### ISSUE TITLE
Indexing in gradient of expected improvement

### ISSUE THREAD

**Issue by aborowska** [gpstuff-dev/gpstuff#43]
This is minor, but in expectedimprovement_eg.m, lines 126-127 (derivative of Ef and Varf wrt. x), indexing should go from 1 to size(x_new,2), not size(x_new,1) as it is now [size(x_new,1) is asserted to be 1 for the gradient to be computed].

**Comment by jpvanhat** [comment]
Hi,

Thank you for pointing this out and sorry for delay in our reply. Which version and/or branch of GPstuff are you using? I guess either v 4.7 or master branch. This bug has already been fixed in the develop branch but since we have not made new stable release for a while it is still missing from master branch.

-Jarno
