### ISSUE TITLE
What's the current developing status?

### ISSUE THREAD

**Issue by astroHaoPeng** [gpstuff-dev/gpstuff#48]
Hi there,

It seems the development has ceased for quite a while. Could anyone provide more information about the development? Like a rough roadmap? Current known problems/issues/bugs? It will be greatly helpful if someone wants to pick up from the last commit.

By the way, is there any fortune that someone would rewrite everything in the MATLAB OOP paradigm?

Best regards.

**Comment by avehtari** [comment]
I and my group have stopped using Matlab. I still do answer some questions and fix bugs. @jpvanhat is still using Matlab and GPstuff in his work, and he is doing more maintenance work than I am. He can tell more about his plans. Note that develop branch has more activity than master.

**Comment by jpvanhat** [comment]
Hi,

As Aki told, me and my group are still actively using GPstuff. However, recently we have mainly used it in its current state (= state of the develop branch) and in addition to bug fixes done only minor improvements and modifications that we've needed in our applied projects. We are still committed to maintaining and improving the code alongside our other activities but we don't have active development plans at the moment. 

Matlab OOP paradigm would be awesome but at the moment I don't have resources to transfer the code there. Moreover, if I wanted to go for that I would very likely change the structure of the package and leave some outdated functionalities away.

If you have some specific ideas or development needs, feel free to tell about those. If they are easy to additions and parallel our needs, then we could collaborate on them.

And if you want to use GPstuff, use develop branch. It is much further than the master branch. The latter refers to the stable release which we have not made for a while..

-Jarno 

Ps. Aki, maybe we should change the settings so that develop branch is the default one?

**Comment by avehtari** [comment]
> Ps. Aki, maybe we should change the settings so that develop branch is the default one?

Ok for me

**Comment by jpvanhat** [comment]
> > Ps. Aki, maybe we should change the settings so that develop branch is the default one?
> 
> Ok for me

default branch update done.

**Comment by astroHaoPeng** [comment]
Hey guys, 
Thanks so much for the clarification. I'm afraid I'm not yet qualified to make any substantial contribution. 
I will give the develop branch a try!
